application: hanhanhangree
version: 1
runtime: python
api_version: 1
 
handlers:
- url: /
  static_files: htdocs/index.html
  upload: /
- url: /
  static_files: htdocs/gadget.xml
  upload: /
- url: /
  static_dir: htdocs